### ISSUE TITLE
Babel plugin naming

### ISSUE THREAD

**Issue by jamiebuilds** [motiz88/babel-plugin-add-jsdoc-properties#4]
Hey @motiz88,

I'm one of the contributors to Babel. I'm concerned about the naming of `babel-plugin-jsdoc` as it is not very descriptive. A better name might be `babel-plugin-add-jsdoc-properties`. 

We all share a namespace here. If people are not descriptive in their plugin name, then we'll end up with all sorts of conflicts. We ask that you be a good citizen within this namespace.

Would you mind updating this plugin to have a more descriptive name?

Thank you

**Comment by motiz88** [comment]
Hi, thanks for the feedback.
Absolutely - I'll get around to changing it in a few days.

**Comment by motiz88** [comment]
Also, on npm: I've deprecated `babel-plugin-jsdoc@<=0.1.4`, [published a deprecation notice in the last README](https://www.npmjs.com/package/babel-plugin-jsdoc) for the old name, and [published under the new name](https://www.npmjs.com/package/babel-plugin-add-jsdoc-properties).

For future reference, if a project ever arises that does need to be called `babel-plugin-jsdoc`, then in consultation with the Babel people I may make the name available to that project for releases versioned 0.2 and above.

Thanks again @thejameskyle! I really appreciate your taking the time to both ask nicely and make a concrete suggestion.

**Comment by jamiebuilds** [comment]
Thanks you @motiz88, it's very much appreciated.
